[[redirects]]
  from = "/manga/*"
  to = "https://api.mangadex.org/manga/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
